FROM node:22-alpine
WORKDIR /app
RUN corepack enable
RUN pnpm config set store-dir /app/.pnpm-store --global
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install
COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]